version: '3'

services:

  osticket:
    build: .
    image: osticket/osticket
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=osticket
      - MYSQL_USER=osticket
      - MYSQL_PASSWORD=testpassword
      - ADMIN_USERNAME=ostadmin
      - ADMIN_PASSWORD=password

      # CHANGE ME
      - INSTALL_SECRET=39a98c1535166cbfe22db4fd844682f1

    links:
      - mysql:mysql
    ports:
      - "80:80"
    restart: always

  mysql:
    image: mariadb
    environment:
       - MYSQL_RANDOM_ROOT_PASSWORD=true
       - MYSQL_DATABASE=osticket
       - MYSQL_USER=osticket
       - MYSQL_PASSWORD=testpassword
    restart: always
